### ISSUE TITLE
Correctly include native libraries into LibUISharp.csproj

### ISSUE THREAD

**Issue by tom-corwin** [tom-corwin/LibUISharp#10]
Any library that referenecs LibUISharp as-is, will recive a `FileNotFoundException`, complaining about not being able to find the libui assembly. I can't seem to find a way to add them to the project and avoid this issue right now, but this needs fixed before anything else.

**Comment by tom-corwin** [comment]
Stupid undocumented bullshit, apparently that workaround doesn't work either! :angry:

**Comment by ashelleyPurdue** [comment]
Hi, I think I figured out the issue!  

Whenever LibUiSharp builds(or any project that references it), everything in the runtimes folder gets copied to the program's output directory.  This is what the /bin/debug folder looks like after compiling:

* Debug
    * ProgramName.dll
    * LibUiSharp.dll
    * runtimes
        * win7-x64
            * native
                * libui.dll
        * linux-x64
            * native
                * you get the idea

If we look at the code where you specify the path the the DLL, though, it looks like this:
`

            private static readonly string[] WinNTLibNames = new[] { "libui.dll" };

            private static readonly string[] LinuxLibNames = new[] { "libui.so", "libui.so.0" };

            private static readonly string[] MacOSLibNames = new[] { "libui.dylib", "libui.A.dylib" };
`

See the problem?  You're looking for "libui.dll" when you should be looking for "runtimes/win7-x64/native/libui.dll" instead.  Changing all of the file names to include the runtimes directory should fix the FileNotFoundException.  I'm preparing a pull request with the fix right now :)

Unfortunately, a different exception rears its head after fixing this one, but that's still progress.
