### ISSUE TITLE
CLS Compliance

### ISSUE THREAD

**Issue by tom-corwin** [tom-corwin/LibUISharp#2]
I need to see about how compliant the library is, and see what needs to be done to be compliant, if not already.

**Comment by IcecreamBurglar** [comment]
Would changing all the `uint`s to `long` or `int` suffice?

**Comment by tom-corwin** [comment]
That should be fine. I'd prefer to make them `long`s if it would marshal correctly back and forth from libui. The only issue I can see is with `LibUISharp.SafeHandles.ControlSafeHandle.GetDangerousControlHandle()`, but that can be marked with `[CLSCompliant(false)]`.

I haven't really looked into what makes an API CLS-compliant, so I don't know much about the specification.

**Comment by tom-corwin** [comment]
Gee, I never thought about adding an assembly-wide `CLSCompliant` attribute then looking at the error list. I guess that makes it a bit easier than I thought, haha :sweat_smile:

**Comment by IcecreamBurglar** [comment]
lol yeah. If we're being perfectly honest I already did that locally before coming here and asking. :D

**Comment by tom-corwin** [comment]
Whoops, forgot to close this I guess.

Fixed by #17
