### ISSUE TITLE
How to use Menu?

### ISSUE THREAD

**Issue by ywxt** [tom-corwin/LibUISharp#25]
Hi,
I found Menu in LibUISharp.However I dot not find any demo to use Menu.
When I ran the following code, a window did not appear and the dotnet process exited at once.
``` csharp
 public class MainWindow : Window
    {
        private readonly Menu _menu=new Menu("Demo");
	
        public MainWindow() : base("LibUISharp Control Gallery", new Size(640, 480), true) => InitializeComponent();
	
        protected sealed override void InitializeComponent()
        {
            IsMargined = true;
            Child = _menu;
            _menu.AddAboutItem(arg=>ShowMessageBox("Demo","Demo"));
            _menu.AddSeparator();
            _menu.AddQuitItem();
        }
    }
```

I hope you can help me.
Thanks.

**Comment by tom-corwin** [comment]
I haven't tested the menu much yet, but if you give a couple. Hours to get off work I'll look into it and update you.

**Comment by ywxt** [comment]
Looking forward to your reply,

**Comment by tom-corwin** [comment]
I just got back to my computer. I'm looking into it now @ywxt

**Comment by tom-corwin** [comment]
Could you also please let me know what OS your are using?

**Comment by ywxt** [comment]
Windows10

**Comment by tom-corwin** [comment]
Alright. I'm linking the new issue you made (#26), as this is the same issue. I also see that I screwed up on interpreting the native API, so I'll have a fix later this evening (it's currently 4:21PM here).

**Comment by tom-corwin** [comment]
I'm pushing a commit now that adds a new example project `SimpleWindowWithMenu`. This show how to properly setup the menu (which is mildly annoying now that I looked at the native API closer). 

Notes for my future reference: There is an [open issue](https://github.com/andlabs/libui/issues/321) and a [closed issue](https://github.com/andlabs/libui/issues/152) that explain that the Menu API is going to ultimately change, and a [closed one](https://github.com/andlabs/libui/issues/152) that explains how it is currently setup in the `libui` repository.

**Comment by tom-corwin** [comment]
I should also mention I'll be making numerous changes, but current code *should/may* run fine.

Either way, the demo projects will be updated accordingly before I merge [the changes](https://github.com/tom-corwin/LibUISharp/tree/api-changes).

**Comment by ywxt** [comment]
Thanks.
