### ISSUE TITLE
The second window is closed…

### ISSUE THREAD

**Issue by ywxt** [tom-corwin/LibUISharp#26]
Hi,
  I was in trouble.

  Try the following code.

```csharp
    class Program
    {
        static void Main(string[] args)
        {
            var app=new Application();
            var win=new Window1();
            app.Run(win);
        }
    }

    class Window1:Window
    {
        private readonly Button _btn=new Button("Show Window2");
        public Window1() : base("Window1") => InitializeComponent();

        protected sealed override void InitializeComponent()
        {
            base.InitializeComponent();
            Child = _btn;
            _btn.Click += (sender, args) =>
            {
                var window2 = new Window2();
                window2.Show();
            };
        }
    }

    class Window2:Window
    {
        public Window2():base("Window2"){}
    }
```
After I closed the window2,the application exited.Why?

Also,the application cannot show Chinese.

Thank in advance for any help.

**Comment by tom-corwin** [comment]
I noticed you didn't use the right Window constructor. Try changing your base constructor call to `base("Window1", 600, 400, true)`

**Comment by tom-corwin** [comment]
The fourth parameter is used to determine whether a menustrip is displayed on the window or not.

**Comment by ywxt** [comment]
Thank you.It is 4:10 now.I will test the code in the morning when I will give you a reply.

**Comment by tom-corwin** [comment]
Refer to #25, as it is the same issue. Marked as a duplicate
