### ISSUE TITLE
Support for uiLoadControlFont

### ISSUE THREAD

**Issue by tom-corwin** [tom-corwin/libuisharp#33]
**This issue is dependant on PR https://github.com/andlabs/libui/pull/388**

**Comment by tom-corwin** [comment]
This should probably be a static function in the `Font` class.

**Comment by cody271** [comment]
@simplexidev `uiLoadControlFont()` has now been [merged](https://github.com/libui-ng/libui-ng/pull/9). Use [`uiFreeFontDescriptor()`](https://github.com/libui-ng/libui-ng/commit/04cbedda6f5a40004290e93c29a1b96e9c223aca) to free.
