### ISSUE TITLE
Can't compile on Linux and .net core 2.0 SDK

### ISSUE THREAD

**Issue by oxyo** [tom-corwin/LibUISharp#9]
Hi, 

I'm trying to compile your library on linux, but I always getting this error:

`src/LibUISharp/FileDialog.cs(2,25): error CS0234: The type or namespace name 'Internal' does not exist in the namespace 'LibUISharp' 
... `

The same error for most files. I'll be grateful to get some hint how to overcome this.

**Comment by oxyo** [comment]
The same error getting on latest VS2017. How to compile this solution?

**Comment by tom-corwin** [comment]
I'll be pushing a few commits today that will allow you to play with what is finished.

**Comment by tom-corwin** [comment]
The error your facing is due to an incomplete commit I pushed. :man_facepalming: I must've forgot to include some files to it. I'm working on them now, so it will be finished in a couple/few hours.

**Comment by tom-corwin** [comment]
The project should build, but the library and demos might not work. I'll have the demos done tonight if not tomorrow to test with.

**Comment by oxyo** [comment]
Thanks :)
